name: Asset-Requisition-System-FE with Docker

on: 
    push:
        branches: [main]
    pull_request: 
        branches: [main]
  
jobs:
    first-job:
        runs-on: windows-latest
        steps:
            - run: node --version
            - run: npm --version
            